import pygame

earth_sprites = [
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp1.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp2.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp3.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp4.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp5.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp6.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp7.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp8.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp9.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp10.png"),
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp11.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp12.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp13.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp14.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp15.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp16.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp17.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp18.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp19.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp20.png"),
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp21.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp22.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp23.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp24.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp25.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp26.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp27.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp28.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp29.png"), 
    pygame.image.load("./Planet Skins/Earth Sprites/earth_sp30.png"),
]